### ISSUE TITLE
Feature Request: Drop In Replacement for torch.nn.MultiheadAttention

### ISSUE THREAD

**Issue by SamuelGabriel** [AminRezaei0x443/memory-efficient-attention#3]
It would super cool, if this could be a drop in replacement for `torch.nn.MultiheadAttention`, thus following the API torch uses so far.

**Comment by AminRezaei0x443** [comment]
Although this is a good idea, the drop-in module isn't implemented because models require more flexibility due to their mechanisms and structures. Instead `efficient_dot_product_attention` is intended to be used within those custom attention modules implementations.

You can simply modify the source code of `MultiheadAttention` or another attention module (such as from hugging face implementations) to incorporate this function. That, I believe, would provide more flexibility.

If you did this and liked to share it, please submit a pull request, and I'll gladly check and merge it.
